# Generated by Django 5.0.1 on 2024-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_remove_likedislike_dislike_remove_likedislike_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ld_like',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='like_dislike',
            field=models.BooleanField(default=None),
        ),
    ]
