# Generated by Django 5.0.1 on 2024-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_remove_product_ld_like_likedislike_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='like_dislike',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
